import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author yarie
 */



public class PanelJuego extends javax.swing.JPanel {

    //Variables
    private Paleta izquierda;
    private Paleta derecha;

    private Jugador jugador1;
    private Jugador jugador2;

    private GestorPartida gestor;

    private Temporizador temporizador;
    
    private static final int X_Izquierda = 20;
    private static final int X_Derecha = 640;
    private static final int Y_Inicial = 120;
    
    /**
     * Creates new form PanelJuego
     */
    
    //Constructor
    public PanelJuego() {
        initComponents();
        
        PanelMesa.setLayout(null); 

        jLabelPaletaIzquierda.setBounds(X_Izquierda, Y_Inicial, 15, 80);
        jLabelPaletaDerecha.setBounds(X_Derecha, Y_Inicial, 15, 80);

        String nombre1 = JOptionPane.showInputDialog("Nombre del jugador 1");
        String nombre2 = JOptionPane.showInputDialog("Nombre del jugador 2");

        jugador1 = new Jugador(nombre1);
        jugador2 = new Jugador(nombre2);

        gestor = new GestorPartida(jugador1, jugador2);
    
        izquierda = new Paleta(X_Izquierda, Y_Inicial);
        derecha = new Paleta(X_Derecha, Y_Inicial);

        lblJugador3.setText(jugador1.getNombre());
        lblJugador2.setText(jugador2.getNombre());

        temporizador = new Temporizador(e -> {
            if ("ACTUALIZAR".equals(e.getActionCommand())) {
                actualizarLabels();
            }

            if ("FIN".equals(e.getActionCommand())) {
                gestor.verificarGanadorRonda();
                if (gestor.quedanMasRondas()) {
                    gestor.iniciarNuevaRonda();
                    temporizador.reiniciarYIniciar();
                } else {
                    mostrarGanador();
                }
                actualizarLabels();
            }
        });
    
        PanelMesa.setFocusable(true);
        java.awt.EventQueue.invokeLater(() -> {
            PanelMesa.requestFocusInWindow();
        });
        actualizarLabels();
        moverPaletas();
    }
    
    private void moverPaletas() {
         PanelMesa.addKeyListener(new java.awt.event.KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent e) {
                
                int tecla = e.getKeyCode();

                if (tecla == KeyEvent.VK_W) {
                    izquierda.moverArriba();
                    jLabelPaletaIzquierda.setLocation(izquierda.getX(), izquierda.getY());
                }

                if (tecla == KeyEvent.VK_S) {
                    izquierda.moverAbajo(PanelMesa.getHeight());
                    jLabelPaletaIzquierda.setLocation(izquierda.getX(),izquierda.getY());
                }

                if (tecla == KeyEvent.VK_UP) {
                    derecha.moverArriba(); 
                    jLabelPaletaDerecha.setLocation(derecha.getX(),derecha.getY());
                }

                if (tecla == KeyEvent.VK_DOWN) {
                    derecha.moverAbajo(PanelMesa.getHeight());
                    jLabelPaletaDerecha.setLocation(derecha.getX(), derecha.getY());
                }
            }
        });
    }  
    
    private void mostrarGanador() {

        Jugador ganador = gestor.obtenerGanadorFinal();

        if (ganador == null) {

            JOptionPane.showMessageDialog(
                this, "La partida terminó en empate.");
        } else {
            JOptionPane.showMessageDialog(
                this, "Ganador: " + ganador.getNombre());
        }
    }
    
    private void actualizarLabels(){
        
        lblJugador3.setText(jugador1.getNombre());
        lblJugador2.setText(jugador2.getNombre());
        
        lblPuntos3.setText("Puntos: " + jugador1.getPuntaje());
        lblPuntos2.setText("Puntos: " + jugador2.getPuntaje());
        
        lblTiempo.setText("Tiempo: " + temporizador.getTiempo());
        
        lblRonda.setText("Ronda: " + gestor.getRondaActual() + "/3");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugador2 = new javax.swing.JLabel();
        lblRonda = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblPuntos2 = new javax.swing.JLabel();
        lblPuntos3 = new javax.swing.JLabel();
        lblDificultad = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnPausar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnIniciar2 = new javax.swing.JButton();
        lblTiempo = new javax.swing.JLabel();
        PanelMesa = new javax.swing.JPanel();
        jLabelPaletaIzquierda = new javax.swing.JLabel();
        jLabelPaletaDerecha = new javax.swing.JLabel();
        JPanelDivision = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador2.setBackground(new java.awt.Color(0, 0, 0));
        lblJugador2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblJugador2.setForeground(new java.awt.Color(0, 0, 0));
        lblJugador2.setText("Jugador 2");
        add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        lblRonda.setBackground(new java.awt.Color(0, 0, 0));
        lblRonda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRonda.setForeground(new java.awt.Color(0, 0, 0));
        lblRonda.setText("Ronda: 1/3");
        add(lblRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 20));

        lblJugador3.setBackground(new java.awt.Color(0, 0, 0));
        lblJugador3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblJugador3.setForeground(new java.awt.Color(0, 0, 0));
        lblJugador3.setText("Jugador 1");
        add(lblJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblPuntos2.setBackground(new java.awt.Color(0, 0, 0));
        lblPuntos2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPuntos2.setForeground(new java.awt.Color(0, 0, 0));
        lblPuntos2.setText("Puntos: 0");
        add(lblPuntos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        lblPuntos3.setBackground(new java.awt.Color(0, 0, 0));
        lblPuntos3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPuntos3.setForeground(new java.awt.Color(0, 0, 0));
        lblPuntos3.setText("Puntos: 0");
        add(lblPuntos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblDificultad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDificultad.setForeground(new java.awt.Color(0, 0, 0));
        lblDificultad.setText("Dificultad:");
        add(lblDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 20));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Normal", "Difícil", "Extremo" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 140, 30));

        btnPausar.setBackground(new java.awt.Color(0, 0, 0));
        btnPausar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnPausar.setForeground(new java.awt.Color(255, 255, 255));
        btnPausar.setText("Pausar");
        btnPausar.addActionListener(this::btnPausarActionPerformed);
        add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 100, 30));

        btnReiniciar.setBackground(new java.awt.Color(0, 0, 0));
        btnReiniciar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);
        add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 110, 30));

        btnIniciar2.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciar2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnIniciar2.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar2.setText("Iniciar");
        btnIniciar2.addActionListener(this::btnIniciar2ActionPerformed);
        add(btnIniciar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 110, 30));

        lblTiempo.setBackground(new java.awt.Color(0, 0, 0));
        lblTiempo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(0, 0, 0));
        lblTiempo.setText("Tiempo: ");
        add(lblTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        PanelMesa.setBackground(new java.awt.Color(204, 204, 204));
        PanelMesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        PanelMesa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPaletaIzquierda.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPaletaIzquierda.setFocusable(false);
        jLabelPaletaIzquierda.setOpaque(true);
        jLabelPaletaIzquierda.setPreferredSize(new java.awt.Dimension(15, 80));
        PanelMesa.add(jLabelPaletaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelPaletaDerecha.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPaletaDerecha.setFocusable(false);
        jLabelPaletaDerecha.setOpaque(true);
        jLabelPaletaDerecha.setPreferredSize(new java.awt.Dimension(15, 80));
        PanelMesa.add(jLabelPaletaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        JPanelDivision.setBackground(new java.awt.Color(0, 0, 0));
        JPanelDivision.setLayout(null);
        PanelMesa.add(JPanelDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 2, 330));

        add(PanelMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 670, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnIniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar2ActionPerformed
        temporizador.iniciar();
        PanelMesa.requestFocusInWindow();
 
    }//GEN-LAST:event_btnIniciar2ActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        if(temporizador.estaActivo()) {
            temporizador.pausar();
        } else {
            temporizador.iniciar();
            PanelMesa.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        gestor.reiniciarPartida();
        temporizador.reiniciar();
        
        izquierda.reiniciar(Y_Inicial);
        derecha.reiniciar(Y_Inicial);

        jLabelPaletaIzquierda.setLocation(X_Izquierda, izquierda.getY());
        jLabelPaletaDerecha.setLocation(X_Derecha, derecha.getY());
       
        actualizarLabels();
        PanelMesa.requestFocusInWindow();
    }//GEN-LAST:event_btnReiniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelDivision;
    private javax.swing.JPanel PanelMesa;
    private javax.swing.JButton btnIniciar2;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelPaletaDerecha;
    public javax.swing.JLabel jLabelPaletaIzquierda;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblPuntos2;
    private javax.swing.JLabel lblPuntos3;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables

    //Getters
    public Jugador getJugador1() {
        return jugador1;
    }

    public Jugador getJugador2() {
        return jugador2;
    }

    public JLabel getjLabelPaletaDerecha() {
        return jLabelPaletaDerecha;
    }

    public JLabel getjLabelPaletaIzquierda() {
        return jLabelPaletaIzquierda;
    }

}
